/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all assets generated by the webpack build (injected by CRA).
precacheAndRoute(self.__WB_MANIFEST);

// Single-page app: serve index.html for all navigation requests.
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(({ request, url }: { request: Request; url: URL }) => {
  if (request.mode !== 'navigate') return false;
  if (url.pathname.startsWith('/_')) return false;
  if (url.pathname.match(fileExtensionRegexp)) return false;
  return true;
}, createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html'));

// Cache the search index (data.json.gz) with StaleWhileRevalidate —
// serves instantly from cache while refreshing in background.
registerRoute(
  ({ url }: { url: URL }) => url.pathname.endsWith('data.json.gz'),
  new StaleWhileRevalidate({ cacheName: 'search-index' })
);

// Cache per-document text files on demand (CacheFirst, expire after 30 days).
registerRoute(
  ({ url }: { url: URL }) => url.pathname.includes('/texts/'),
  new CacheFirst({
    cacheName: 'doc-texts',
    plugins: [new ExpirationPlugin({ maxEntries: 500, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  })
);

// Allow the service worker to skip waiting and activate immediately on update.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
