on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/seppo0010/buscador-corte-idh:latest
          cache-from: type=registry,ref=ghcr.io/seppo0010/buscador-corte-idh:buildcache
          cache-to: type=registry,ref=ghcr.io/seppo0010/buscador-corte-idh:buildcache,mode=max

  publish:
    needs: [build-docker-image]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
