on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/seppo0010/buscador-corte-idh:latest
      options: "--cap-add=SYS_ADMIN"
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: /tmp/data
          key: data
      - name: Run
        run: ./run.sh
        env:
          DATA_DIR: /tmp/data
